#!/bin/bash
#SBATCH --job-name=adapt_bins_test
#SBATCH --error=output/bins_%j.err
#SBATCH --output=output/bins_%j.out
#SBATCH --time=00:01:00
#SBATCH --nodes=1                  # Request 2 nodes
#SBATCH --ntasks-per-node=4         # 1 core per node
#SBATCH --cluster=merlin6
#SBATCH --partition=hourly           # Non-GPU partition, check cluster for correct partition
#SBATCH --account=merlin
##SBATCH --exclusive
##SBATCH --nodelist=merlin-c-001   # Modify node list if needed for non-GPU nodes

##unlink core
## ulimit -c unlimited # rols the size of core dumps that can be generated by a process when it crashes

## source /psi/home/liemen_a/.bashrc
## load_ippl

export OMP_PROC_BIND=spread # I guess?
export OMP_PLACES=threads

cd /data/user/liemen_a/build_ippl/test/binning/
mpirun ./Binning_pic3d 32 32 32 1000 3 --info 10



