function makeTwoParticleData()
% Compute several results of the two particle model with different parameters
% and save them in files
%
% the beam pipe radius is 5[mm]
%

a=5;

%% Alu

Csection = 'circular';
cs = 'Circ';
Material = 'aluminium';
ma = 'Al';
Direction = 'longitudinal';
di = 'Lo';
Conductivity = 'ac';
co = 'AC';
Lbunch = 294;
Charge = 0.8;
K = 0.20536314319923724;
c = 299792458;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));




% Two particle model longitudinal
t=5
for i = 2:Lbunch
[x,dx] = twoParticleTest(0, t, 0.0001,i,a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K, c, wake);
deltaX(i-1) = dx;
end

PrintSignal(deltaX, ['twoParticle/way_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Comparison of startposition and position after ' num2str(t) 's in the relative position [\mum] in Matlab \n# from head to tail', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

% Compute the energy spread
load('bunchProfile.mat')
energy = compenergy(K, Charge, wake, bunchProfile);

PrintSignal(energy, ['twoParticle/energy_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'],...
    ['#Energy Spread in Matlab \n# from head to tail', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);




Csection = 'circular';
cs = 'Circ';
Material = 'aluminium';
ma = 'Al';
Direction = 'transversal';
di = 'Tr';
Conductivity = 'ac';
co = 'AC';
Lbunch = 256;
Charge = 0.8;
K = 0.20536314319923724;
c = 299792458;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));


% Two particle model transversal
t=5
for i = 2:Lbunch
[x,dx] = twoParticleTest(0, t, 0.0001,i,a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K, c, wake);
deltaX(i-1) = dx;
end

PrintSignal(deltaX, ['twoParticle/way_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Comparison of startposition and position after ' num2str(t) 's in the relative position [\mum] in Matlab \n# from head to tail', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

% Compute the energy spread
load('bunchProfile.mat')
energy = compenergy(K, Charge, wake, bunchProfile);

PrintSignal(energy, ['twoParticle/energy_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'],...
    ['#Energy Spread in Matlab \n# from head to tail', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);




%% Copper
Csection = 'circular';
cs = 'Circ';
Material = 'copper';
ma = 'Cu';
Direction = 'longitudinal';
di = 'Lo';
Conductivity = 'ac';
co = 'AC';
Lbunch = 256;
Charge = 0.8;
K = 0.20536314319923724;
c = 299792458;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));




% Two particle model longitudinal
t=5
for i = 2:Lbunch
[x,dx] = twoParticleTest(0, t, 0.0001,i,a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K, c, wake);
deltaX(i-1) = dx;
end

PrintSignal(deltaX, ['twoParticle/way_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Comparison of startposition and position after ' num2str(t) 's in the relative position [\mum] in Matlab \n# from head to tail', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

% Compute the energy spread
load('bunchProfile.mat')
energy = compenergy(K, Charge, wake, bunchProfile);

PrintSignal(energy, ['twoParticle/energy_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'],...
    ['#Energy Spread in Matlab \n# from head to tail', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);




Csection = 'circular';
cs = 'Circ';
Material = 'copper';
ma = 'Cu';
Direction = 'transversal';
di = 'Tr';
Conductivity = 'ac';
co = 'AC';
Lbunch = 256;
Charge = 0.8;
K = 0.20536314319923724;
c = 299792458;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));




% Two particle model longitudinal
t=5
for i = 2:Lbunch
[x,dx] = twoParticleTest(0, t, 0.0001,i,a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K, c, wake);
deltaX(i-1) = dx;
end

PrintSignal(deltaX, ['twoParticle/way_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Comparison of startposition and position after ' num2str(t) 's in the relative position [\mum] in Matlab \n# from head to tail', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

% Compute the energy spread
load('bunchProfile.mat')
energy = compenergy(K, Charge, wake, bunchProfile);

PrintSignal(energy, ['twoParticle/energy_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'],...
    ['#Energy Spread in Matlab \n# from head to tail', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

