function makeCompWakeSerie()
% Compute several wakefields with different parameters
% and save them in files
%
% the beam pipe radius is 5[mm]
%
a = 5;

%% AC Section
Csection = 'circular';
cs = 'Circ';
Material = 'aluminium';
ma = 'Al';
Direction = 'longitudinal';
di = 'Lo';
Conductivity = 'ac';
co = 'AC';
Lbunch = 256;
Charge = 0.8;
K = 0.20536314319923724;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));

PrintSignal(wake, ['wakeFields/wake_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

PrintSignal(wakeFFT, ['wakeFields/wakeFFT_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#FFT of the Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

Csection = 'circular';
cs = 'Circ';
Material = 'aluminium';
ma = 'Al';
Direction = 'transversal';
di = 'Tr';
Conductivity = 'ac';
co = 'AC';
Lbunch = 256;
Charge = 0.8;
K = 0.20536314319923724;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));

PrintSignal(wake, ['wakeFields/wake_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

PrintSignal(wakeFFT, ['wakeFields/wakeFFT_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#FFT of the Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

Csection = 'circular';
cs = 'Circ';
Material = 'copper';
ma = 'Cu';
Direction = 'longitudinal';
di = 'Lo';
Conductivity = 'ac';
co = 'AC';
Lbunch = 256;
Charge = 0.8;
K = 0.20536314319923724;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));

PrintSignal(wake, ['wakeFields/wake_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

PrintSignal(wakeFFT, ['wakeFields/wakeFFT_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#FFT of the Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

Csection = 'circular';
cs = 'Circ';
Material = 'copper';
ma = 'Cu';
Direction = 'transversal';
di = 'Tr';
Conductivity = 'ac';
co = 'AC';
Lbunch = 256;
Charge = 0.8;
K = 0.20536314319923724;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));

PrintSignal(wake, ['wakeFields/wake_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

PrintSignal(wakeFFT, ['wakeFields/wakeFFT_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#FFT of the Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

%% DC Section
% Csection = 'circular';
% cs = 'Circ';
% Material = 'aluminium';
% ma = 'Al';
% Direction = 'longitudinal';
% di = 'Lo';
% Conductivity = 'dc';
% co = 'DC';
% Lbunch = 256;
% Charge = 0.8;
% K = 0.20536314319923724;
% 
% wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
% wakeFFT = abs(fft(wake));
% 
% PrintSignal(wake, ['wakeFields/wake_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Wakefiled calculated in Matlab', ...
%     '\n#Material: ', Material, ...
%     '\n#Direction: ', Direction, ...
%     '\n#Conductivity: ', Conductivity, ...
%     '\n#Form: Circular', ...
%     '\n#Tube radius: ', num2str(a), ...
%     '\n#Bunch Length: ', num2str(Lbunch), ...
%     '\n#Charge: ', num2str(Charge), ...
%     '\n#K: ', num2str(K) ...
%     '\n\n']);
% 
% PrintSignal(wakeFFT, ['wakeFields/wakeFFT_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#FFT of the Wakefiled calculated in Matlab', ...
%     '\n#Material: ', Material, ...
%     '\n#Direction: ', Direction, ...
%     '\n#Conductivity: ', Conductivity, ...
%     '\n#Form: Circular', ...
%     '\n#Tube radius: ', num2str(a), ...
%     '\n#Bunch Length: ', num2str(Lbunch), ...
%     '\n#Charge: ', num2str(Charge), ...
%     '\n#K: ', num2str(K) ...
%     '\n\n']);

Csection = 'circular';
cs = 'Circ';
Material = 'aluminium';
ma = 'Al';
Direction = 'transversal';
di = 'Tr';
Conductivity = 'dc';
co = 'DC';
Lbunch = 256;
Charge = 0.8;
K = 0.20536314319923724;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));

PrintSignal(wake, ['wakeFields/wake_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

PrintSignal(wakeFFT, ['wakeFields/wakeFFT_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#FFT of the Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

% Csection = 'circular';
% cs = 'Circ';
% Material = 'copper';
% ma = 'Cu';
% Direction = 'longitudinal';
% di = 'Lo';
% Conductivity = 'dc';
% co = 'DC';
% Lbunch = 256;
% Charge = 0.8;
% K = 0.20536314319923724;
% 
% wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
% wakeFFT = abs(fft(wake));
% 
% PrintSignal(wake, ['wakeFields/wake_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Wakefiled calculated in Matlab', ...
%     '\n#Material: ', Material, ...
%     '\n#Direction: ', Direction, ...
%     '\n#Conductivity: ', Conductivity, ...
%     '\n#Form: Circular', ...
%     '\n#Tube radius: ', num2str(a), ...
%     '\n#Bunch Length: ', num2str(Lbunch), ...
%     '\n#Charge: ', num2str(Charge), ...
%     '\n#K: ', num2str(K) ...
%     '\n\n']);
% 
% PrintSignal(wakeFFT, ['wakeFields/wakeFFT_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#FFT of the Wakefiled calculated in Matlab', ...
%     '\n#Material: ', Material, ...
%     '\n#Direction: ', Direction, ...
%     '\n#Conductivity: ', Conductivity, ...
%     '\n#Form: Circular', ...
%     '\n#Tube radius: ', num2str(a), ...
%     '\n#Bunch Length: ', num2str(Lbunch), ...
%     '\n#Charge: ', num2str(Charge), ...
%     '\n#K: ', num2str(K) ...
%     '\n\n']);

Csection = 'circular';
cs = 'Circ';
Material = 'copper';
ma = 'Cu';
Direction = 'transversal';
di = 'Tr';
Conductivity = 'dc';
co = 'DC';
Lbunch = 256;
Charge = 0.8;
K = 0.20536314319923724;

wake = cmpwake(a, Direction, Csection, Material, Conductivity, Lbunch, Charge, K);
wakeFFT = abs(fft(wake));

PrintSignal(wake, ['wakeFields/wake_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);

PrintSignal(wakeFFT, ['wakeFields/wakeFFT_',di,'_',cs,'_', ma,'_',co,'_',num2str(a),'_Mat.dat'], ['#FFT of the Wakefiled calculated in Matlab', ...
    '\n#Material: ', Material, ...
    '\n#Direction: ', Direction, ...
    '\n#Conductivity: ', Conductivity, ...
    '\n#Form: Circular', ...
    '\n#Tube radius: ', num2str(a), ...
    '\n#Bunch Length: ', num2str(Lbunch), ...
    '\n#Charge: ', num2str(Charge), ...
    '\n#K: ', num2str(K) ...
    '\n\n']);
