/* ./config.h.  Generated by configure.  */
/* ./config.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <AztecOO.h> header file. */
/* #undef HAVE_AZTECOO_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <Epetra_LinearProblem.h> header file. */
/* #undef HAVE_EPETRA_LINEARPROBLEM_H */

/* Define to 1 if you have the <Epetra_Map.h> header file. */
/* #undef HAVE_EPETRA_MAP_H */

/* Define to 1 if you have the <Epetra_Operator.h> header file. */
/* #undef HAVE_EPETRA_OPERATOR_H */

/* Define to 1 if you have the <Epetra_Vector.h> header file. */
/* #undef HAVE_EPETRA_VECTOR_H */

/* Define to 1 if you have the <gsl/gsl_histogram2d.h> header file. */
#define HAVE_GSL_GSL_HISTOGRAM2D_H 1

/* Define to 1 if you have the <gsl/gsl_rng.h> header file. */
#define HAVE_GSL_GSL_RNG_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <ml_epetra_utils.h> header file. */
/* #undef HAVE_ML_EPETRA_UTILS_H */

/* Define to 1 if you have the <ml_include.h> header file. */
/* #undef HAVE_ML_INCLUDE_H */

/* Define to 1 if you have the <ml_MatrixFreePreconditioner.h> header file. */
/* #undef HAVE_ML_MATRIXFREEPRECONDITIONER_H */

/* Define to 1 if you have the <ml_MultiLevelOperator.h> header file. */
/* #undef HAVE_ML_MULTILEVELOPERATOR_H */

/* Define to 1 if you have the <ml_MultiLevelPreconditioner.h> header file. */
/* #undef HAVE_ML_MULTILEVELPRECONDITIONER_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <Teuchos_CommandLineProcessor.hpp> header file.
   */
/* #undef HAVE_TEUCHOS_COMMANDLINEPROCESSOR_HPP */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "opal"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "andreas.adelmann@psi.ch"

/* Define to the full name of this package. */
#define PACKAGE_NAME "OPAL"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "OPAL 1.1.8"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "opal"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.1.8"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* repository svn version */
#define SVN_VERSION "11730M"

/* Version number of package */
#define VERSION "1.1.8"
