#################################################
##BEGIN OF makefile "makefile" - using the gnu-compiler g++
##This file is used by the Make command.
###################################################

FILE=opal_user_guide

all:	$(FILE).tex
	pdflatex $(FILE).tex
	pdflatex $(FILE).tex
clean:
	rm -f *~ *.lot *.bbl *.aux *.blg *.log *.dvi *.ps *.toc *.idx *.lof *.pdf
