#!/usr/bin/env python3
"""Generate six unpadded DBA cells with explicit entrance poses (no ELEMEDGE).

This is a geometry/return regression fixture, not a matched closed orbit or an
analytic finite-fringe matrix. The historical five-element study is untouched.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
from pathlib import Path
import re
import subprocess
import time

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parents[2]


def geometry(hgap=0.1):
    """Nominal body intervals tile [0,C]; field support never enters this walk."""
    x = z = angle = s = 0.0
    rows = []
    rho, bend_angle = 2.0, math.pi / 6
    for cell in range(1, 7):
        for stem, kind, length in [
            ("B1", "SBEND", rho * bend_angle), ("D1", "DRIFT", 1.0),
            ("Q", "QUADRUPOLE", 0.2), ("D2", "DRIFT", 1.0),
            ("B2", "SBEND", rho * bend_angle),
        ]:
            rows.append(dict(name=f"C{cell}_{stem}", kind=kind, length_m=length,
                             s_begin_m=s, s_end_m=s + length, x_m=x, z_m=z,
                             theta_rad=-angle))
            if kind == "SBEND":
                dx, dz = rho * (math.cos(bend_angle) - 1), rho * math.sin(bend_angle)
            else:
                dx, dz = 0.0, length
            x += math.cos(angle) * dx - math.sin(angle) * dz
            z += math.sin(angle) * dx + math.cos(angle) * dz
            s += length
            if kind == "SBEND":
                angle += bend_angle
    assert math.hypot(x, z) < 1e-12
    assert abs(angle - 2 * math.pi) < 1e-14
    return dict(elements=rows, design_circumference_m=s, closure_m=math.hypot(x, z),
                total_bend_rad=angle, cells=6, hgap_m=hgap, fint=0.1,
                quadrupole_k1_m2=-6.371966681365967)


def deck(model, method="DOP853", dt=1e-11):
    lines = [
        '// Generated by build_ring.py; nominal lengths, no fringe padding.',
        'OPTION, ECHO=FALSE, PSDUMPFREQ=0, STATDUMPFREQ=0, VERSION=10900, ASCIIDUMP=FALSE;',
        'OPTION, ENABLELINEARTRANSFERMAPS=TRUE, LINEARTRANSFERMAPRICHARDSON=1,',
        f'        LINEARTRANSFERMAPINTEGRATOR="{method}",',
        '        LINEARTRANSFERMAPSTEPS={1e-4,1e-4,1e-4,1e-4,1e-4,1e-4};',
        'TITLE, STRING="Six-cell finite-fringe DBA RING; unmatched launch";',
        'REAL P0=0.2505104781131461;',
    ]
    for row in model["elements"]:
        attrs = f'L={row["length_m"]:.17g}'
        if row["kind"] == "SBEND":
            attrs += f', ANGLE={math.pi/6:.17g}, HGAP={model["hgap_m"]:g}, FINT=0.1'
            # Native SBEND forbids explicit HAPERT/APERTURE when HGAP=0.
            # The hard-edge control therefore uses its default bend aperture.
            if model['hgap_m'] > 0:
                attrs += ', HAPERT=0.5'
        else:
            # Finite transverse domains prevent opposite ring sides being selected by an
            # infinite straight slab. These apertures are not longitudinal fringe cutoffs.
            attrs += ', APERTURE="RECTANGLE(1.0,0.2)"'
            if row["kind"] == "QUADRUPOLE":
                attrs += ', K1=-6.371966681365967'
        attrs += f', X={row["x_m"]:.17g}, Y=0, Z={row["z_m"]:.17g}'
        attrs += f', THETA={row["theta_rad"]:.17g}, PHI=0, PSI=0'
        lines.append(f'{row["name"]}: {row["kind"]}, {attrs};')
    lines.append('LATTICE: RING = (' + ', '.join(r["name"] for r in model["elements"]) + ');')
    distribution = (ROOT.parent / 'reference-particle.txt').resolve()
    lines += [
        f'DIST: DISTRIBUTION, TYPE=FROMFILE, FNAME="{distribution}", NPARTDIST=1;',
        'SOURCE: EMISSIONSOURCE, DISTRIBUTION=DIST;',
        'SOURCES: EMISSIONSOURCELIST=(SOURCE);',
        'FS: FIELDSOLVER, TYPE=NONE, NX=16, NY=16, NZ=16,',
        '    PARFFTX=TRUE, PARFFTY=TRUE, PARFFTZ=TRUE,',
        '    BCFFTX=OPEN, BCFFTY=OPEN, BCFFTZ=OPEN, BBOXINCR=1, GREENSF=INTEGRATED;',
        'BEAM1: BEAM, PARTICLE=ELECTRON, NALLOC=1,',
        '       BCHARGE=1.6021766339999998e-19, SOURCES=SOURCES, CHARGE=-1;',
        f'TRACK, LINE=LATTICE, BEAM=BEAM1, MAXSTEPS=1, DT={dt:.17g},',
        f'       ZSTOP={model["design_circumference_m"]:.17g};',
        'RUN, METHOD="PARALLEL", FIELDSOLVER=FS;',
        'ENDTRACK;', 'QUIT;',
    ]
    return '\n'.join(lines) + '\n'


def diagnostics(stdout):
    """Read printed diagnostics; do not reinterpret slope coordinates as canonical."""
    result = {}
    for key, label in [
        ('reference_return_length_m', 'RING reference return length'),
        ('return_displacement_m', 'RING return displacement'),
        ('relative_momentum_mismatch', 'relative momentum mismatch'),
        ('determinant_residual', '|det(M) - 1|'),
        ('canonical_form_residual', 'max_ij |(M^T J M - J)_ij|'),
    ]:
        match = re.search(re.escape(label) + r' = ([0-9.eE+\-]+)', stdout)
        if match:
            result[key] = float(match.group(1))
    block = re.search(r'Combined one-turn linear transfer map[^\n]*\n((?:[^\n]*\n){6})', stdout)
    if block:
        matrix = [[float(v) for v in re.findall(r'[+-]?\d+\.\d+e[+-]\d+', line)]
                  for line in block.group(1).splitlines()]
        if len(matrix) == 6 and all(len(row) == 6 for row in matrix):
            if all(math.isfinite(v) for row in matrix for v in row):
                result['matrix'] = matrix
                result['R16'], result['R26'] = matrix[0][5], matrix[1][5]
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT / 'case')
    parser.add_argument('--run', action='store_true')
    parser.add_argument('--binary', type=Path, default=REPO / 'omp-build/src/opalx')
    parser.add_argument('--method', choices=['BORIS', 'RK4', 'DOP853'], default='DOP853')
    parser.add_argument('--dt', type=float, default=1e-11)
    parser.add_argument('--hgap', type=float, default=0.1, help='Bend half gap in metres (0: hard edge)')
    args = parser.parse_args()
    if not math.isfinite(args.dt) or args.dt <= 0:
        parser.error('--dt must be finite and positive')
    if not math.isfinite(args.hgap) or args.hgap < 0:
        parser.error('--hgap must be finite and nonnegative')
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    if (output / 'map-3-ring.out').exists():
        parser.error('Choose a fresh output directory; existing run output is preserved')
    model = geometry(args.hgap)
    text = deck(model, args.method, args.dt)
    (output / 'map-3-ring.in').write_text(text)
    (output / 'geometry.json').write_text(json.dumps(model, indent=2) + '\n')
    if not args.run:
        print(output / 'map-3-ring.in')
        return
    binary = args.binary.resolve()
    # Capture provenance before launch, so a rebuild cannot relabel the executable used.
    binary_sha = hashlib.sha256(binary.read_bytes()).hexdigest()
    git_head = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=REPO, text=True).strip()
    source_diff = subprocess.check_output(['git', 'diff', '--', 'src', 'unit_tests'], cwd=REPO)
    (output / 'source.patch').write_bytes(source_diff)
    env = os.environ | {'OMP_NUM_THREADS': '1', 'OMP_PROC_BIND': 'false'}
    command = [str(binary), 'map-3-ring.in', '--info', '2']
    started = time.monotonic()
    timed_out = False
    with (output / 'map-3-ring.out').open('w') as stdout:
        try:
            run = subprocess.run(command, cwd=output, env=env, stdout=stdout,
                                 stderr=subprocess.STDOUT, timeout=600)
            returncode = run.returncode
        except subprocess.TimeoutExpired:
            returncode, timed_out = 124, True
    stdout = (output / 'map-3-ring.out').read_text()
    result = dict(command=command, ranks=1, method=args.method, dt_s=args.dt,
                  hgap_m=args.hgap, fint=model['fint'],
                  bend_aperture=('HAPERT=0.5; vertical half width HGAP'
                                 if args.hgap > 0 else 'default (explicit aperture forbidden at HGAP=0)'),
                  returncode=returncode, timed_out=timed_out, elapsed_s=time.monotonic() - started,
                  design_circumference_m=model['design_circumference_m'],
                  input_sha256=hashlib.sha256(text.encode()).hexdigest(),
                  binary_sha256=binary_sha, git_head=git_head,
                  worktree_diff_sha256=hashlib.sha256(source_diff).hexdigest(),
                  closed_orbit_solved=False, external_code_comparison=False)
    result.update(diagnostics(stdout))
    result['status'] = ('OK' if returncode == 0 and 'matrix' in result
                        and 'reference_return_length_m' in result else 'FAILED')
    (output / 'result.json').write_text(json.dumps(result, indent=2) + '\n')
    print(json.dumps(result, indent=2))
    if result['status'] != 'OK':
        raise SystemExit(1)


if __name__ == '__main__':
    main()
